// figscript-package/rollup.config.mjs
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';
import dts from 'rollup-plugin-dts';
import peerDepsExternal from 'rollup-plugin-peer-deps-external';

export default [
  {
    // Main bundle for JavaScript (CommonJS and ES Module)
    input: 'src/index.ts',
    output: [
      {
        file: 'dist/cjs/index.js',
        format: 'cjs',
        sourcemap: true,
      },
      {
        file: 'dist/esm/index.js',
        format: 'esm',
        sourcemap: true,
      },
    ],
    plugins: [
      peerDepsExternal(),
      resolve(),
      commonjs(),
      typescript({ // This plugin will primarily handle JS transpilation now for the build script
        tsconfig: './tsconfig.json',
        // Explicitly tell the plugin NOT to emit declarations here,
        // as the `types:generate` script (tsc) now handles it.
        declaration: false,
        declarationDir: undefined, // Explicitly set to undefined to avoid TS5069
      }),
    ],
    external: ['react', 'react-dom'],
  },
  {
    // Bundle for type definitions (consumes .d.ts files generated by `npm run types:generate`)
    input: 'dist/types/index.d.ts', 
    output: [{ file: 'dist/types/index.d.ts', format: 'esm' }],
    plugins: [dts()],
    external: [/\.css$/],
  },
];