// figscript-package/rollup.config.mjs
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';
import dts from 'rollup-plugin-dts';
import peerDepsExternal from 'rollup-plugin-peer-deps-external';

export default [
  {
    // Main bundle for JavaScript (CommonJS and ES Module)
    input: 'src/index.ts',
    output: [
      {
        file: 'dist/cjs/index.js',
        format: 'cjs',
        sourcemap: true,
      },
      {
        file: 'dist/esm/index.js',
        format: 'esm',
        sourcemap: true,
      },
    ],
    plugins: [
      peerDepsExternal(),
      resolve(),
      commonjs(),
      typescript({
        tsconfig: './tsconfig.json',
        declaration: true, // Explicitly instruct the plugin to generate declarations
        declarationDir: './dist/types', // Explicitly set the output directory for these .d.ts files
        rootDir: './src', // Define the root directory for TypeScript source files
        exclude: [ // Ensure plugin respects exclusions
            "node_modules/**",
            "dist/**",
            "rollup.config.mjs",
            "**/*.test.ts",
            "**/*.spec.ts"
        ]
      }),
    ],
    external: ['react', 'react-dom'],
  },
  {
    // Bundle for type definitions
    input: 'dist/types/index.d.ts', // This MUST be generated by the typescript plugin in the step above
    output: [{ file: 'dist/types/index.d.ts', format: 'esm' }],
    plugins: [dts()],
    external: [/\.css$/],
  },
];