// src/components/FigScript/parser/types.ts

/**
 * Defines the standard structure for the result of a FigScript property parser.
 */
export interface FigScriptParseResult {
  /** An array of Tailwind CSS class names generated by the parser. */
  classes: string[];
  /** An array of error messages encountered during parsing. For syntax/validation errors. */
  errors: string[];
  /** An array of warning messages. For minor issues, suggestions, or unsupported features. */
  warnings: string[];
}

/**
 * Represents a token that can either be a simple string value
 * or a key-value pair (e.g., "propName=value").
 */
export type FigScriptToken = string | { key: string; value: string };

/**
 * Represents the different layout modes FigScript can operate in.
 * - 'AUTO': Corresponds to Figma's Auto Layout.
 * - 'STANDARD': Corresponds to Figma's regular frame layout (manual positioning and sizing).
 * - 'UNKNOWN': The mode could not be determined, or parsing has not yet established it.
 */
export type LayoutMode = 'AUTO' | 'STANDARD' | 'UNKNOWN';
